FROM node:20-alpine AS base

# Make the env variables available via arg and env
ARG VITE_BACKEND_HOST
ENV VITE_BACKEND_HOST=$VITE_BACKEND_HOST

WORKDIR /app

COPY package*.json/ ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .


# This is the target for the development profile
FROM base AS dev

EXPOSE 5173

CMD ["npm", "run", "dev"]


# This is the target of the frontend test profile
FROM base AS test

CMD ["npm", "run", "test"]


# This will sets up the production environment
FROM base AS prod-setup

RUN npm run build


FROM nginx:stable-alpine3.23-perl AS prod

COPY --from=prod-setup /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

ENTRYPOINT ["nginx", "-c", "/etc/nginx/nginx.conf"]
CMD ["-g", "daemon off;"]