stages:
  - test-frontend
  - test-backend
  - test-frontend-build
  - build-images

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "development"
    - when: never

default:
  before_script:
    - docker compose --profile frontend-test down -v || true
    - docker info
  after_script:
    - docker compose --profile frontend-test down -v


test-frontend:
  stage: test-frontend
  when: always
  tags:
   - docker-pipeline
  script:
    - docker compose --profile test-frontend up --build --exit-code-from frontend-test # --exit-code-from frontend-test = compose will exit with whatever exit code the service exited with (wont pass a failing pipeline)
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: frontend_coverage/coverage/cobertura-coverage.xml

test-backend:
  stage: test-backend
  when: always
  tags:
    - docker-pipeline
  script:
    - docker compose --profile test-backend up --build --abort-on-container-exit --exit-code-from backend-test # --abort-on-container-exit = when backend container exits, db container be forced to exit

test-frontend-build:
  stage: test-frontend-build
  when: always
  tags:
   - docker-pipeline
  script:
    - docker build ./frontend/ --target prod

build-images-main:
  stage: build-images
  when: always
  tags:
    - docker-pipeline
  rules:
    # - if: $CI_COMMIT_BRANCH == "main"
  script:
    - echo "Logging into registry..."
    - echo "$DOCKER_PAT" | docker login -u $DOCKER_USER --password-stdin
    - echo "This is the docker registry image value - $DOCKER_REGISTRY_IMAGE"
    - echo "Building the frontend image..."
    - docker build -t $DOCKER_REGISTRY_IMAGE:frontend-latest ./frontend/ --target prod
    - echo "Building the backend image..."
    - docker build -t $DOCKER_REGISTRY_IMAGE:backend-latest ./backend/
    - echo "Pushing the frontend image to the container registry..."
    - docker push $DOCKER_REGISTRY_IMAGE:frontend-latest
    - echo "Pushing the backend image to the container registry..."
    - docker push $DOCKER_REGISTRY_IMAGE:backend-latest