FROM python:3.12-alpine AS backend-dev

RUN apk add --no-cache libstdc++

WORKDIR /backend

# Copy over pyproject.toml and allow it to be cached
COPY ./pyproject.toml /backend/pyproject.toml

RUN pip install --no-cache-dir --upgrade -e .

RUN python -m spacy download en_core_web_lg

# copy over alembic folders and files
COPY ./alembic /backend/alembic
COPY ./alembic.ini /backend/alembic.ini

# Copy over the fastapi application
COPY ./app /backend/app

ENV PYTHONPATH=/backend

# This is to run the app on port 8000 - Currently using dev!
CMD ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]