"""new initial schema

Revision ID: 0194bfac404e
Revises: 
Create Date: 2026-03-06 18:00:21.544766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0194bfac404e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_file',
    sa.Column('scan_file_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('scan_file_id')
    )
    op.create_index(op.f('ix_scan_file_scan_file_id'), 'scan_file', ['scan_file_id'], unique=False)
    op.create_table('scan_file_detection',
    sa.Column('scan_file_detection_id', sa.Integer(), nullable=False),
    sa.Column('scan_file_id', sa.Integer(), nullable=True),
    sa.Column('sensitivity_subcategory', sa.String(length=64), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_file_id'], ['scan_file.scan_file_id'], ),
    sa.PrimaryKeyConstraint('scan_file_detection_id')
    )
    op.create_index(op.f('ix_scan_file_detection_scan_file_detection_id'), 'scan_file_detection', ['scan_file_detection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_file_detection_scan_file_detection_id'), table_name='scan_file_detection')
    op.drop_table('scan_file_detection')
    op.drop_index(op.f('ix_scan_file_scan_file_id'), table_name='scan_file')
    op.drop_table('scan_file')
    # ### end Alembic commands ###
