"""Added used column to invites table

Revision ID: 066740d44ec6
Revises: 331e2abdad7d
Create Date: 2026-02-19 22:58:31.547971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066740d44ec6'
down_revision: Union[str, Sequence[str], None] = '331e2abdad7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'used')
    # ### end Alembic commands ###
