"""Added foreign key relationship between workspaces and users

Revision ID: 06748f3a137f
Revises: 875b09f3d2ce
Create Date: 2026-03-08 17:06:49.931109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06748f3a137f'
down_revision: Union[str, Sequence[str], None] = '875b09f3d2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workspaces', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.drop_column('workspaces', 'user_id')
    # ### end Alembic commands ###
