"""Added threshold to RolePermission

Revision ID: 086554f8868d
Revises: f8aa8880f454
Create Date: 2026-02-19 18:25:38.696914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086554f8868d'
down_revision: Union[str, Sequence[str], None] = 'f8aa8880f454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permission', sa.Column('threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_permission', 'threshold')
    # ### end Alembic commands ###
