"""Added relationship between workspaces and pending users tables

Revision ID: 095d984c6a3e
Revises: 5a8cb396359a
Create Date: 2026-03-30 18:56:53.645494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095d984c6a3e'
down_revision: Union[str, Sequence[str], None] = '5a8cb396359a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
