"""Changed datatype for images to MEDIUMBLOB

Revision ID: 09d70c2cde72
Revises: 06748f3a137f
Create Date: 2026-03-08 17:18:58.643053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09d70c2cde72'
down_revision: Union[str, Sequence[str], None] = '06748f3a137f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'image',
               existing_type=sa.BLOB(),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
