"""Recreated invites table

Revision ID: 0bd6e9f0db7a
Revises: d7153f3f771c
Create Date: 2026-03-02 14:59:25.456837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd6e9f0db7a'
down_revision: Union[str, Sequence[str], None] = 'd7153f3f771c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('token', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'token')
    # ### end Alembic commands ###
