"""Added pending_user_role

Revision ID: 188284f384a1
Revises: 6269bb4febd6
Create Date: 2026-03-28 15:57:02.354039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188284f384a1'
down_revision: Union[str, Sequence[str], None] = '6269bb4febd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_user_role',
    sa.Column('pending_user_role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pending_users.user_id'], ),
    sa.PrimaryKeyConstraint('pending_user_role_id')
    )
    op.create_index(op.f('ix_pending_user_role_pending_user_role_id'), 'pending_user_role', ['pending_user_role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_user_role_pending_user_role_id'), table_name='pending_user_role')
    op.drop_table('pending_user_role')
    # ### end Alembic commands ###
