"""Changed scan_files model name to scan_file for clarity fixed

Revision ID: 18d73f12bc52
Revises: b83656bfd6fa
Create Date: 2026-03-06 11:50:40.695070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18d73f12bc52'
down_revision: Union[str, Sequence[str], None] = 'b83656bfd6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_file',
    sa.Column('scan_file_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('scan_file_id')
    )
    op.create_index(op.f('ix_scan_file_scan_file_id'), 'scan_file', ['scan_file_id'], unique=False)
    op.drop_index(op.f('ix_scan_files_scan_file_id'), table_name='scan_files')
    op.drop_table('scan_files')
    op.drop_constraint(op.f('scan_file_detection_ibfk_1'), 'scan_file_detection', type_='foreignkey')
    op.create_foreign_key(None, 'scan_file_detection', 'scan_file', ['scan_file_id'], ['scan_file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_file_detection', type_='foreignkey')
    op.create_foreign_key(op.f('scan_file_detection_ibfk_1'), 'scan_file_detection', 'scan_files', ['scan_file_id'], ['scan_file_id'])
    op.create_table('scan_files',
    sa.Column('scan_file_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('scan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], name=op.f('scan_files_ibfk_1')),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('scan_files_ibfk_2')),
    sa.PrimaryKeyConstraint('scan_file_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_scan_files_scan_file_id'), 'scan_files', ['scan_file_id'], unique=False)
    op.drop_index(op.f('ix_scan_file_scan_file_id'), table_name='scan_file')
    op.drop_table('scan_file')
    # ### end Alembic commands ###
