"""Reconfigured relationsship between invites and pending_users with ondelete CASCADE

Revision ID: 2c8aa1c20318
Revises: 3a21fe95d3d3
Create Date: 2026-03-10 22:23:35.646580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8aa1c20318'
down_revision: Union[str, Sequence[str], None] = '3a21fe95d3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invites_ibfk_1'), 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'pending_users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(op.f('invites_ibfk_1'), 'invites', 'pending_users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
