"""Added a column last_updated in Roles

Revision ID: 2d0debd8d7ac
Revises: 985d60b89e17
Create Date: 2026-04-17 18:27:15.652336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0debd8d7ac'
down_revision: Union[str, Sequence[str], None] = '985d60b89e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('last_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'last_updated')
    # ### end Alembic commands ###
