"""Create files table

Revision ID: 2f8f8361052c
Revises: 
Create Date: 2026-02-18 18:32:09.795629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8f8361052c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_extension', sa.String(length=16), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_file_file_id'), 'file', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_file_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
