"""Added the invites table

Revision ID: 331e2abdad7d
Revises: 6c7569a6e2fa
Create Date: 2026-02-19 22:37:41.532291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331e2abdad7d'
down_revision: Union[str, Sequence[str], None] = '6c7569a6e2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('invite_id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invites_invite_id'), 'invites', ['invite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_invite_id'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
