"""Added passive delete to pending_users table

Revision ID: 3a21fe95d3d3
Revises: a3d8edbdc7dd
Create Date: 2026-03-10 22:18:14.365180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a21fe95d3d3'
down_revision: Union[str, Sequence[str], None] = 'a3d8edbdc7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
