"""updated the user model to store the driveId for the user

Revision ID: 3d8b79a9c248
Revises: 6502e27a1f3d
Create Date: 2026-03-24 23:32:14.753111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8b79a9c248'
down_revision: Union[str, Sequence[str], None] = '6502e27a1f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('driveId', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'driveId')
    # ### end Alembic commands ###
