"""recreating db

Revision ID: 3d8f4e72a341
Revises: 43a1db65759f
Create Date: 2026-04-12 13:53:40.668124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8f4e72a341'
down_revision: Union[str, Sequence[str], None] = '43a1db65759f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_group',
    sa.Column('duplicate_group_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('duplicate_group_id')
    )
    op.create_index(op.f('ix_duplicate_group_duplicate_group_id'), 'duplicate_group', ['duplicate_group_id'], unique=False)
    op.create_table('duplicate_scan_result',
    sa.Column('duplicate_scan_result_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_group_id', sa.Integer(), nullable=True),
    sa.Column('scan_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['duplicate_group.duplicate_group_id'], ),
    sa.ForeignKeyConstraint(['scan_file_id'], ['scan_file.scan_file_id'], ),
    sa.PrimaryKeyConstraint('duplicate_scan_result_id')
    )
    op.create_index(op.f('ix_duplicate_scan_result_duplicate_scan_result_id'), 'duplicate_scan_result', ['duplicate_scan_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duplicate_scan_result_duplicate_scan_result_id'), table_name='duplicate_scan_result')
    op.drop_table('duplicate_scan_result')
    op.drop_index(op.f('ix_duplicate_group_duplicate_group_id'), table_name='duplicate_group')
    op.drop_table('duplicate_group')
    # ### end Alembic commands ###
