"""set drive_id for ingestion_file and folder tables to be indexed

Revision ID: 3eaeabb08f9d
Revises: 5dee69a07cc3
Create Date: 2026-03-25 00:47:32.485041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eaeabb08f9d'
down_revision: Union[str, Sequence[str], None] = '5dee69a07cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_folder_drive_id'), 'folder', ['drive_id'], unique=False)
    op.create_index(op.f('ix_ingestion_file_drive_id'), 'ingestion_file', ['drive_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_file_drive_id'), table_name='ingestion_file')
    op.drop_index(op.f('ix_folder_drive_id'), table_name='folder')
    # ### end Alembic commands ###
