"""Updated the invites table again to just have used column

Revision ID: 3f56f2deaf5c
Revises: 8c86d17fe773
Create Date: 2026-03-14 12:31:04.645138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f56f2deaf5c'
down_revision: Union[str, Sequence[str], None] = '8c86d17fe773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
