"""created tables for user-files and user-folders. Also added names to extra arguements

Revision ID: 408c198ad208
Revises: e5e9b7cf4a05
Create Date: 2026-03-16 13:03:11.437833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408c198ad208'
down_revision: Union[str, Sequence[str], None] = 'e5e9b7cf4a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_folders',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('folder_id', 'user_id')
    )
    op.create_index('rev_idx_user_folders', 'user_folders', ['user_id', 'folder_id'], unique=False)
    op.create_table('user_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['ingestion_file.ingestion_file_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('file_id', 'user_id')
    )
    op.create_index('rev_idx_user_files', 'user_files', ['user_id', 'file_id'], unique=False)
    op.drop_index(op.f('graph_id'), table_name='folder')
    op.drop_index(op.f('ix_folder_folder_id'), table_name='folder')
    op.create_unique_constraint('uq_graph_id', 'folder', ['graph_id'])
    op.drop_index(op.f('ix_ingestion_file_ingestion_file_id'), table_name='ingestion_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ingestion_file_ingestion_file_id'), 'ingestion_file', ['ingestion_file_id'], unique=False)
    op.drop_constraint('uq_graph_id', 'folder', type_='unique')
    op.create_index(op.f('ix_folder_folder_id'), 'folder', ['folder_id'], unique=False)
    op.create_index(op.f('graph_id'), 'folder', ['graph_id'], unique=True)
    op.drop_index('rev_idx_user_files', table_name='user_files')
    op.drop_table('user_files')
    op.drop_index('rev_idx_user_folders', table_name='user_folders')
    op.drop_table('user_folders')
    # ### end Alembic commands ###
