"""Added new column type to pending users table

Revision ID: 52578f89f6a6
Revises: 095d984c6a3e
Create Date: 2026-03-30 19:34:53.367658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52578f89f6a6'
down_revision: Union[str, Sequence[str], None] = '095d984c6a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_users', sa.Column('type', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_users', 'type')
    # ### end Alembic commands ###
