"""Added on delete cascade to role_id column in user_roles table

Revision ID: 55655f6106b6
Revises: 01a2dca43319
Create Date: 2026-04-06 18:10:34.837861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55655f6106b6'
down_revision: Union[str, Sequence[str], None] = '01a2dca43319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_role_ibfk_1'), 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['role_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_ibfk_1'), 'user_role', 'role', ['role_id'], ['role_id'])
    # ### end Alembic commands ###
