"""create db again

Revision ID: 59e5fb714110
Revises: 
Create Date: 2026-04-22 02:44:30.357712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e5fb714110'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_emails',
    sa.Column('violation_email_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('violation_email_id')
    )
    op.create_index(op.f('ix_violation_emails_violation_email_id'), 'violation_emails', ['violation_email_id'], unique=False)
    op.create_table('workspace_detection_sensitivity',
    sa.Column('workspace_detection_sensitivity_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('sensitivity_subcategory_id', sa.Integer(), nullable=False),
    sa.Column('is_high', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sensitivity_subcategory_id'], ['sensitivity_subcategory.sensitivity_subcategory_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_detection_sensitivity_id')
    )
    op.create_index(op.f('ix_workspace_detection_sensitivity_workspace_detection_sensitivity_id'), 'workspace_detection_sensitivity', ['workspace_detection_sensitivity_id'], unique=False)
    op.add_column('role', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('user_files_ibfk_1'), 'user_files', type_='foreignkey')
    op.drop_constraint(op.f('user_files_ibfk_2'), 'user_files', type_='foreignkey')
    op.create_foreign_key(None, 'user_files', 'ingestion_file', ['file_id'], ['ingestion_file_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_files', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_folders_ibfk_2'), 'user_folders', type_='foreignkey')
    op.drop_constraint(op.f('user_folders_ibfk_1'), 'user_folders', type_='foreignkey')
    op.create_foreign_key(None, 'user_folders', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_folders', 'folder', ['folder_id'], ['folder_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_folders', type_='foreignkey')
    op.drop_constraint(None, 'user_folders', type_='foreignkey')
    op.create_foreign_key(op.f('user_folders_ibfk_1'), 'user_folders', 'folder', ['folder_id'], ['folder_id'])
    op.create_foreign_key(op.f('user_folders_ibfk_2'), 'user_folders', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.create_foreign_key(op.f('user_files_ibfk_2'), 'user_files', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('user_files_ibfk_1'), 'user_files', 'ingestion_file', ['file_id'], ['ingestion_file_id'])
    op.drop_column('role', 'last_updated')
    op.drop_index(op.f('ix_workspace_detection_sensitivity_workspace_detection_sensitivity_id'), table_name='workspace_detection_sensitivity')
    op.drop_table('workspace_detection_sensitivity')
    op.drop_index(op.f('ix_violation_emails_violation_email_id'), table_name='violation_emails')
    op.drop_table('violation_emails')
    # ### end Alembic commands ###
