"""Added relationship between workspaces and pending users tables

Revision ID: 5a8cb396359a
Revises: a7369104ef3b
Create Date: 2026-03-30 18:54:16.240285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8cb396359a'
down_revision: Union[str, Sequence[str], None] = 'a7369104ef3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
