"""ensured that the driveId for folders and ingestion files are no longer nullable

Revision ID: 5dee69a07cc3
Revises: 8cb6a3d2c570
Create Date: 2026-03-25 00:38:20.269607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5dee69a07cc3'
down_revision: Union[str, Sequence[str], None] = '8cb6a3d2c570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folder', 'drive_id',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('ingestion_file', 'drive_id',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingestion_file', 'drive_id',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('folder', 'drive_id',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
