"""updated user_folder model to use foreign key constraint

Revision ID: 6502e27a1f3d
Revises: 408c198ad208
Create Date: 2026-03-22 13:00:51.550601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6502e27a1f3d'
down_revision: Union[str, Sequence[str], None] = '408c198ad208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_folders', 'folder', ['folder_id'], ['folder_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_folders', type_='foreignkey')
    # ### end Alembic commands ###
