"""Created tables for scan, scan_files, scan_file_result

Revision ID: 69fd26f22930
Revises: 96ca9d63b3d1
Create Date: 2026-03-03 10:31:30.897544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fd26f22930'
down_revision: Union[str, Sequence[str], None] = '96ca9d63b3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=False)
    op.create_table('scan_files',
    sa.Column('scan_file_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('scan_file_id')
    )
    op.create_index(op.f('ix_scan_files_scan_file_id'), 'scan_files', ['scan_file_id'], unique=False)
    op.create_table('scan_file_result',
    sa.Column('scan_file_result_id', sa.Integer(), nullable=False),
    sa.Column('scan_file_id', sa.Integer(), nullable=True),
    sa.Column('name_count', sa.Integer(), nullable=False),
    sa.Column('phone_count', sa.Integer(), nullable=False),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.Column('address_count', sa.Integer(), nullable=False),
    sa.Column('postcode_count', sa.Integer(), nullable=False),
    sa.Column('number_plate_count', sa.Integer(), nullable=False),
    sa.Column('iban_count', sa.Integer(), nullable=False),
    sa.Column('vat_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scan_file_id'], ['scan_files.scan_file_id'], ),
    sa.PrimaryKeyConstraint('scan_file_result_id')
    )
    op.create_index(op.f('ix_scan_file_result_scan_file_result_id'), 'scan_file_result', ['scan_file_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_file_result_scan_file_result_id'), table_name='scan_file_result')
    op.drop_table('scan_file_result')
    op.drop_index(op.f('ix_scan_files_scan_file_id'), table_name='scan_files')
    op.drop_table('scan_files')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
