"""Added new table ViolationEmail

Revision ID: 7e12c21731e4
Revises: 8d2c4568cf0d
Create Date: 2026-04-14 14:11:49.470299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e12c21731e4'
down_revision: Union[str, Sequence[str], None] = '8d2c4568cf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_emails',
    sa.Column('violation_email_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('violation_email_id')
    )
    op.create_index(op.f('ix_violation_emails_violation_email_id'), 'violation_emails', ['violation_email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violation_emails_violation_email_id'), table_name='violation_emails')
    op.drop_table('violation_emails')
    # ### end Alembic commands ###
