"""Describe change

Revision ID: 8394f091157f
Revises: 52170b405bd0
Create Date: 2026-04-05 17:01:58.180151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8394f091157f'
down_revision: Union[str, Sequence[str], None] = '52170b405bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('scan_file_ibfk_1'), 'scan_file', type_='foreignkey')
    op.create_foreign_key(None, 'scan_file', 'ingestion_file', ['file_id'], ['ingestion_file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_file', type_='foreignkey')
    op.create_foreign_key(op.f('scan_file_ibfk_1'), 'scan_file', 'file', ['file_id'], ['file_id'])
    # ### end Alembic commands ###
