"""Made all columns in invites table not null

Revision ID: 8c86d17fe773
Revises: f810b3a53247
Create Date: 2026-03-13 20:26:41.585157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c86d17fe773'
down_revision: Union[str, Sequence[str], None] = 'f810b3a53247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invites', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('invites', 'expiry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('invites', 'token',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('invites', 'used',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invites', 'used',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('invites', 'token',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('invites', 'expiry_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('invites', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
