"""updated the folder and ingestion file tables

Revision ID: 8cb6a3d2c570
Revises: 3d8b79a9c248
Create Date: 2026-03-25 00:29:06.431987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb6a3d2c570'
down_revision: Union[str, Sequence[str], None] = '3d8b79a9c248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('drive_id', sa.Text(), nullable=True))
    op.add_column('ingestion_file', sa.Column('drive_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_file', 'drive_id')
    op.drop_column('folder', 'drive_id')
    # ### end Alembic commands ###
