"""Added graph file id and file name to files model

Revision ID: 96ca9d63b3d1
Revises: 2f8f8361052c
Create Date: 2026-02-19 15:55:21.674748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ca9d63b3d1'
down_revision: Union[str, Sequence[str], None] = '2f8f8361052c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('graph_file_id', sa.String(length=128), nullable=True))
    op.add_column('file', sa.Column('file_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_name')
    op.drop_column('file', 'graph_file_id')
    # ### end Alembic commands ###
