"""Created tables again

Revision ID: a0892576c95a
Revises: ce19c2f7ae14
Create Date: 2026-03-07 14:17:54.938988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0892576c95a'
down_revision: Union[str, Sequence[str], None] = 'ce19c2f7ae14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_pending_users_user_id'), 'pending_users', ['user_id'], unique=False)
    op.alter_column('user', 'oid',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'oid',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.drop_index(op.f('ix_pending_users_user_id'), table_name='pending_users')
    op.drop_table('pending_users')
    # ### end Alembic commands ###
