"""Added ondelete CASCADE to invites table (foreign key with pending_users

Revision ID: a3d8edbdc7dd
Revises: eb4520e159d8
Create Date: 2026-03-10 22:10:34.335196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d8edbdc7dd'
down_revision: Union[str, Sequence[str], None] = 'eb4520e159d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invites_ibfk_1'), 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'pending_users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(op.f('invites_ibfk_1'), 'invites', 'pending_users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
