"""Added relationship between workspaces and pending users tables

Revision ID: a7369104ef3b
Revises: ef31ec3a66f5
Create Date: 2026-03-30 18:50:10.855808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7369104ef3b'
down_revision: Union[str, Sequence[str], None] = 'ef31ec3a66f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
