"""Added ondelete CASCADE back to user_files and user_folders

Revision ID: afc0dedd1b78
Revises: 985d60b89e17
Create Date: 2026-04-19 19:54:25.396104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc0dedd1b78'
down_revision: Union[str, Sequence[str], None] = '985d60b89e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_files_ibfk_1'), 'user_files', type_='foreignkey')
    op.drop_constraint(op.f('user_files_ibfk_2'), 'user_files', type_='foreignkey')
    op.create_foreign_key(None, 'user_files', 'ingestion_file', ['file_id'], ['ingestion_file_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_files', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_folders_ibfk_2'), 'user_folders', type_='foreignkey')
    op.drop_constraint(op.f('user_folders_ibfk_1'), 'user_folders', type_='foreignkey')
    op.create_foreign_key(None, 'user_folders', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_folders', 'folder', ['folder_id'], ['folder_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_folders', type_='foreignkey')
    op.drop_constraint(None, 'user_folders', type_='foreignkey')
    op.create_foreign_key(op.f('user_folders_ibfk_1'), 'user_folders', 'folder', ['folder_id'], ['folder_id'])
    op.create_foreign_key(op.f('user_folders_ibfk_2'), 'user_folders', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.drop_constraint(None, 'user_files', type_='foreignkey')
    op.create_foreign_key(op.f('user_files_ibfk_2'), 'user_files', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('user_files_ibfk_1'), 'user_files', 'ingestion_file', ['file_id'], ['ingestion_file_id'])
    # ### end Alembic commands ###
