"""Hopefully ON CASCADE works now

Revision ID: b639db88dd3f
Revises: 07a24a2e1b21
Create Date: 2026-03-10 22:34:48.944519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b639db88dd3f'
down_revision: Union[str, Sequence[str], None] = '07a24a2e1b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
