"""adding column to users

Revision ID: b7b6a82d53ca
Revises: 421f1a9b9d2e
Create Date: 2026-03-15 13:40:29.071661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7b6a82d53ca'
down_revision: Union[str, Sequence[str], None] = '421f1a9b9d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_file',
    sa.Column('ingestion_file_id', sa.Integer(), nullable=False),
    sa.Column('graph_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('hash_type', sa.String(length=20), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('web_url', sa.Text(), nullable=False),
    sa.Column('parent_graph_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['parent_graph_id'], ['folder.graph_id'], ),
    sa.PrimaryKeyConstraint('ingestion_file_id')
    )
    op.create_index(op.f('ix_ingestion_file_graph_id'), 'ingestion_file', ['graph_id'], unique=False)
    op.create_index(op.f('ix_ingestion_file_ingestion_file_id'), 'ingestion_file', ['ingestion_file_id'], unique=False)
    op.create_index(op.f('ix_ingestion_file_parent_graph_id'), 'ingestion_file', ['parent_graph_id'], unique=False)
    op.alter_column('folder', 'graph_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('invites', sa.Column('status', sa.String(length=16), nullable=True))
    op.add_column('invites', sa.Column('used', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('invites_ibfk_1'), 'invites', type_='foreignkey')
    op.drop_constraint(op.f('invites_ibfk_2'), 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'pending_users', ['user_id'], ['user_id'])
    op.drop_column('invites', 'workspace_id')
    op.add_column('user', sa.Column('username', sa.String(length=254), nullable=False))
    op.add_column('user', sa.Column('refresh', sa.BLOB(), nullable=False))
    op.add_column('user', sa.Column('deltaLink', sa.Text(), nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=11), nullable=True))
    op.drop_column('user', 'deltaLink')
    op.drop_column('user', 'refresh')
    op.drop_column('user', 'username')
    op.add_column('invites', sa.Column('workspace_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(op.f('invites_ibfk_2'), 'invites', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('invites_ibfk_1'), 'invites', 'pending_users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('invites', 'used')
    op.drop_column('invites', 'status')
    op.alter_column('folder', 'graph_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_ingestion_file_parent_graph_id'), table_name='ingestion_file')
    op.drop_index(op.f('ix_ingestion_file_ingestion_file_id'), table_name='ingestion_file')
    op.drop_index(op.f('ix_ingestion_file_graph_id'), table_name='ingestion_file')
    op.drop_table('ingestion_file')
    # ### end Alembic commands ###
