"""Changed scan_files model name to scan_file for clarity

Revision ID: b83656bfd6fa
Revises: 8627811c547a
Create Date: 2026-03-06 11:49:57.184874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83656bfd6fa'
down_revision: Union[str, Sequence[str], None] = '8627811c547a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
