"""Updates user_workspace, user_roles and pending_user_workspace with ONCASCADE=delete field

Revision ID: c23e5a1623cd
Revises: 52578f89f6a6
Create Date: 2026-04-01 18:12:26.230006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23e5a1623cd'
down_revision: Union[str, Sequence[str], None] = '52578f89f6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pending_user_workspace_ibfk_2'), 'pending_user_workspace', type_='foreignkey')
    op.drop_constraint(op.f('pending_user_workspace_ibfk_1'), 'pending_user_workspace', type_='foreignkey')
    op.create_foreign_key(None, 'pending_user_workspace', 'pending_users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pending_user_workspace', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_role_ibfk_2'), 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_workspace_ibfk_1'), 'user_workspace', type_='foreignkey')
    op.drop_constraint(op.f('user_workspace_ibfk_2'), 'user_workspace', type_='foreignkey')
    op.create_foreign_key(None, 'user_workspace', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_workspace', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_workspace', type_='foreignkey')
    op.drop_constraint(None, 'user_workspace', type_='foreignkey')
    op.create_foreign_key(op.f('user_workspace_ibfk_2'), 'user_workspace', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(op.f('user_workspace_ibfk_1'), 'user_workspace', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_ibfk_2'), 'user_role', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'pending_user_workspace', type_='foreignkey')
    op.drop_constraint(None, 'pending_user_workspace', type_='foreignkey')
    op.create_foreign_key(op.f('pending_user_workspace_ibfk_1'), 'pending_user_workspace', 'pending_users', ['user_id'], ['user_id'])
    op.create_foreign_key(op.f('pending_user_workspace_ibfk_2'), 'pending_user_workspace', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
