"""Nuked database AGAIN

Revision ID: c68840d9f772
Revises: e935902c73f5
Create Date: 2026-04-23 01:08:44.920890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68840d9f772'
down_revision: Union[str, Sequence[str], None] = 'e935902c73f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unknown_user_folders',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.folder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id', 'email')
    )
    op.create_index('rev_idx_unknown_user_folders', 'unknown_user_folders', ['email', 'folder_id'], unique=False)
    op.create_table('unknown_user_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['ingestion_file.ingestion_file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'email')
    )
    op.create_index('rev_idx_unknown_user_files', 'unknown_user_files', ['email', 'file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('rev_idx_unknown_user_files', table_name='unknown_user_files')
    op.drop_table('unknown_user_files')
    op.drop_index('rev_idx_unknown_user_folders', table_name='unknown_user_folders')
    op.drop_table('unknown_user_folders')
    # ### end Alembic commands ###
