"""Created tables again

Revision ID: c9059027b3ab
Revises: a0892576c95a
Create Date: 2026-03-07 14:27:07.038936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9059027b3ab'
down_revision: Union[str, Sequence[str], None] = 'a0892576c95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invites_ibfk_1'), 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'pending_users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(op.f('invites_ibfk_1'), 'invites', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
