"""organisation scan models

Revision ID: e144ad1d4023
Revises: d7153f3f771c
Create Date: 2026-03-06 17:14:23.383758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e144ad1d4023'
down_revision: Union[str, Sequence[str], None] = 'd7153f3f771c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naming_convention',
    sa.Column('naming_convention_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('naming_convention_id')
    )
    op.create_index(op.f('ix_naming_convention_naming_convention_id'), 'naming_convention', ['naming_convention_id'], unique=False)
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.create_table('scans',
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=False)
    op.create_table('sensitivity_category',
    sa.Column('sensitivity_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('sensitivity_category_id')
    )
    op.create_index(op.f('ix_sensitivity_category_sensitivity_category_id'), 'sensitivity_category', ['sensitivity_category_id'], unique=False)
    op.create_table('scan_files',
    sa.Column('scan_file_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('scan_file_id')
    )
    op.create_index(op.f('ix_scan_files_scan_file_id'), 'scan_files', ['scan_file_id'], unique=False)
    op.create_table('scan_naming_convention',
    sa.Column('scan_naming_convention_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('naming_convention_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['naming_convention_id'], ['naming_convention.naming_convention_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('scan_naming_convention_id')
    )
    op.create_index(op.f('ix_scan_naming_convention_scan_naming_convention_id'), 'scan_naming_convention', ['scan_naming_convention_id'], unique=False)
    op.create_table('sensitivity_subcategory',
    sa.Column('sensitivity_subcategory_id', sa.Integer(), nullable=False),
    sa.Column('sensitivity_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['sensitivity_category_id'], ['sensitivity_category.sensitivity_category_id'], ),
    sa.PrimaryKeyConstraint('sensitivity_subcategory_id')
    )
    op.create_index(op.f('ix_sensitivity_subcategory_sensitivity_subcategory_id'), 'sensitivity_subcategory', ['sensitivity_subcategory_id'], unique=False)
    op.create_table('naming_convention_scan_result',
    sa.Column('naming_convention_scan_result_id', sa.Integer(), nullable=False),
    sa.Column('scan_file_id', sa.Integer(), nullable=False),
    sa.Column('scan_naming_convention_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('suggested_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['scan_file_id'], ['scan_files.scan_file_id'], ),
    sa.ForeignKeyConstraint(['scan_naming_convention_id'], ['scan_naming_convention.scan_naming_convention_id'], ),
    sa.PrimaryKeyConstraint('naming_convention_scan_result_id')
    )
    op.create_index(op.f('ix_naming_convention_scan_result_naming_convention_scan_result_id'), 'naming_convention_scan_result', ['naming_convention_scan_result_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('sensitivity_subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['sensitivity_subcategory_id'], ['sensitivity_subcategory.sensitivity_subcategory_id'], ),
    sa.PrimaryKeyConstraint('role_permission_id')
    )
    op.create_index(op.f('ix_role_permission_role_permission_id'), 'role_permission', ['role_permission_id'], unique=False)
    op.drop_column('file', 'file_extension')
    op.add_column('invites', sa.Column('token', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'token')
    op.add_column('file', sa.Column('file_extension', mysql.VARCHAR(length=16), nullable=True))
    op.drop_index(op.f('ix_role_permission_role_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_naming_convention_scan_result_naming_convention_scan_result_id'), table_name='naming_convention_scan_result')
    op.drop_table('naming_convention_scan_result')
    op.drop_index(op.f('ix_sensitivity_subcategory_sensitivity_subcategory_id'), table_name='sensitivity_subcategory')
    op.drop_table('sensitivity_subcategory')
    op.drop_index(op.f('ix_scan_naming_convention_scan_naming_convention_id'), table_name='scan_naming_convention')
    op.drop_table('scan_naming_convention')
    op.drop_index(op.f('ix_scan_files_scan_file_id'), table_name='scan_files')
    op.drop_table('scan_files')
    op.drop_index(op.f('ix_sensitivity_category_sensitivity_category_id'), table_name='sensitivity_category')
    op.drop_table('sensitivity_category')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_naming_convention_naming_convention_id'), table_name='naming_convention')
    op.drop_table('naming_convention')
    # ### end Alembic commands ###
