"""Updated workspace model to take into account new relationship

Revision ID: e6fa0b037cfe
Revises: 6600a66a1581
Create Date: 2026-03-22 19:42:52.206704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fa0b037cfe'
down_revision: Union[str, Sequence[str], None] = '6600a66a1581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
