"""Initial migration after merge with development

Revision ID: eb4520e159d8
Revises: 
Create Date: 2026-03-08 23:39:49.396091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb4520e159d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('graph_file_id', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=128), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_file_file_id'), 'file', ['file_id'], unique=False)
    op.create_table('naming_convention',
    sa.Column('naming_convention_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('naming_convention_id')
    )
    op.create_index(op.f('ix_naming_convention_naming_convention_id'), 'naming_convention', ['naming_convention_id'], unique=False)
    op.create_table('pending_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_pending_users_user_id'), 'pending_users', ['user_id'], unique=False)
    op.create_table('refresh_family',
    sa.Column('refresh_family_id', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('refresh_family_id')
    )
    op.create_index(op.f('ix_refresh_family_refresh_family_id'), 'refresh_family', ['refresh_family_id'], unique=False)
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.create_table('scans',
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=False)
    op.create_table('sensitivity_category',
    sa.Column('sensitivity_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('sensitivity_category_id')
    )
    op.create_index(op.f('ix_sensitivity_category_sensitivity_category_id'), 'sensitivity_category', ['sensitivity_category_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('oid', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_oid'), 'user', ['oid'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('invites',
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['pending_users.user_id'], ),
    sa.PrimaryKeyConstraint('invite_id')
    )
    op.create_index(op.f('ix_invites_invite_id'), 'invites', ['invite_id'], unique=False)
    op.create_table('refresh',
    sa.Column('refresh_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('refresh_family_id', sa.Integer(), nullable=True),
    sa.Column('replaced_by', sa.Integer(), nullable=True),
    sa.Column('replaced_at', sa.DateTime(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['refresh_family_id'], ['refresh_family.refresh_family_id'], ),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh.refresh_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_id')
    )
    op.create_index(op.f('ix_refresh_refresh_family_id'), 'refresh', ['refresh_family_id'], unique=False)
    op.create_index(op.f('ix_refresh_refresh_id'), 'refresh', ['refresh_id'], unique=False)
    op.create_index(op.f('ix_refresh_token'), 'refresh', ['token'], unique=True)
    op.create_table('scan_file',
    sa.Column('scan_file_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.file_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('scan_file_id')
    )
    op.create_index(op.f('ix_scan_file_scan_file_id'), 'scan_file', ['scan_file_id'], unique=False)
    op.create_table('scan_naming_convention',
    sa.Column('scan_naming_convention_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('naming_convention_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['naming_convention_id'], ['naming_convention.naming_convention_id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('scan_naming_convention_id')
    )
    op.create_index(op.f('ix_scan_naming_convention_scan_naming_convention_id'), 'scan_naming_convention', ['scan_naming_convention_id'], unique=False)
    op.create_table('sensitivity_subcategory',
    sa.Column('sensitivity_subcategory_id', sa.Integer(), nullable=False),
    sa.Column('sensitivity_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['sensitivity_category_id'], ['sensitivity_category.sensitivity_category_id'], ),
    sa.PrimaryKeyConstraint('sensitivity_subcategory_id')
    )
    op.create_index(op.f('ix_sensitivity_subcategory_sensitivity_subcategory_id'), 'sensitivity_subcategory', ['sensitivity_subcategory_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', mysql.MEDIUMBLOB(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('naming_convention_scan_result',
    sa.Column('naming_convention_scan_result_id', sa.Integer(), nullable=False),
    sa.Column('scan_file_id', sa.Integer(), nullable=False),
    sa.Column('scan_naming_convention_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('suggested_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['scan_file_id'], ['scan_file.scan_file_id'], ),
    sa.ForeignKeyConstraint(['scan_naming_convention_id'], ['scan_naming_convention.scan_naming_convention_id'], ),
    sa.PrimaryKeyConstraint('naming_convention_scan_result_id')
    )
    op.create_index(op.f('ix_naming_convention_scan_result_naming_convention_scan_result_id'), 'naming_convention_scan_result', ['naming_convention_scan_result_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('sensitivity_subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['sensitivity_subcategory_id'], ['sensitivity_subcategory.sensitivity_subcategory_id'], ),
    sa.PrimaryKeyConstraint('role_permission_id')
    )
    op.create_index(op.f('ix_role_permission_role_permission_id'), 'role_permission', ['role_permission_id'], unique=False)
    op.create_table('scan_file_detection',
    sa.Column('scan_file_detection_id', sa.Integer(), nullable=False),
    sa.Column('scan_file_id', sa.Integer(), nullable=True),
    sa.Column('sensitivity_subcategory', sa.String(length=64), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_file_id'], ['scan_file.scan_file_id'], ),
    sa.PrimaryKeyConstraint('scan_file_detection_id')
    )
    op.create_index(op.f('ix_scan_file_detection_scan_file_detection_id'), 'scan_file_detection', ['scan_file_detection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_file_detection_scan_file_detection_id'), table_name='scan_file_detection')
    op.drop_table('scan_file_detection')
    op.drop_index(op.f('ix_role_permission_role_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_naming_convention_scan_result_naming_convention_scan_result_id'), table_name='naming_convention_scan_result')
    op.drop_table('naming_convention_scan_result')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_sensitivity_subcategory_sensitivity_subcategory_id'), table_name='sensitivity_subcategory')
    op.drop_table('sensitivity_subcategory')
    op.drop_index(op.f('ix_scan_naming_convention_scan_naming_convention_id'), table_name='scan_naming_convention')
    op.drop_table('scan_naming_convention')
    op.drop_index(op.f('ix_scan_file_scan_file_id'), table_name='scan_file')
    op.drop_table('scan_file')
    op.drop_index(op.f('ix_refresh_token'), table_name='refresh')
    op.drop_index(op.f('ix_refresh_refresh_id'), table_name='refresh')
    op.drop_index(op.f('ix_refresh_refresh_family_id'), table_name='refresh')
    op.drop_table('refresh')
    op.drop_index(op.f('ix_invites_invite_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_oid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sensitivity_category_sensitivity_category_id'), table_name='sensitivity_category')
    op.drop_table('sensitivity_category')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_refresh_family_refresh_family_id'), table_name='refresh_family')
    op.drop_table('refresh_family')
    op.drop_index(op.f('ix_pending_users_user_id'), table_name='pending_users')
    op.drop_table('pending_users')
    op.drop_index(op.f('ix_naming_convention_naming_convention_id'), table_name='naming_convention')
    op.drop_table('naming_convention')
    op.drop_index(op.f('ix_file_file_id'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
