"""made null for dev purposes

Revision ID: ef09e82eae03
Revises: ea079acd41ad
Create Date: 2026-03-24 11:47:59.068068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef09e82eae03'
down_revision: Union[str, Sequence[str], None] = 'ea079acd41ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
