"""Created a new table between to hold both user and workspaces foreign keye

Revision ID: f1d87baf4769
Revises: e6fa0b037cfe
Create Date: 2026-03-22 20:05:11.781772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1d87baf4769'
down_revision: Union[str, Sequence[str], None] = 'e6fa0b037cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workspace',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id')
    )
    op.drop_constraint(op.f('user_ibfk_1'), 'user', type_='foreignkey')
    op.drop_column('user', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('workspace_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_ibfk_1'), 'user', 'workspaces', ['workspace_id'], ['id'])
    op.drop_table('user_workspace')
    # ### end Alembic commands ###
