"""Fields should not be nullable for current columns in users table

Revision ID: f3c8c059846f
Revises: 93ec34cc55e3
Create Date: 2026-02-22 14:56:40.732014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3c8c059846f'
down_revision: Union[str, Sequence[str], None] = '93ec34cc55e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'firstname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'surname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'oid',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'oid',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('user', 'surname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
